src/Entity/SaisonHotel.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SaisonHotelRepository")
 */
class SaisonHotel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Hotel", inversedBy="saisonHotels")
     */
    private $id_hotel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getIdHotel(): ?Hotel
    {
        return $this->id_hotel;
    }

    public function setIdHotel(?Hotel $id_hotel): self
    {
        $this->id_hotel = $id_hotel;

        return $this;
    }

   
}

src/Form/SaisonHotelType.php
<?php

namespace App\Form;

use App\Entity\SaisonHotel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SaisonHotelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prix')
            ->add('date_debut')
            ->add('date_fin')
            ->add('id_hotel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SaisonHotel::class,
        ]);
    }
}

src/Controller/SaisonHotelController.php
<?php

namespace App\Controller;

use App\Entity\SaisonHotel;
use App\Form\SaisonHotelType;
use App\Repository\SaisonHotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/saison/hotel")
 */
class SaisonHotelController extends AbstractController
{
    /**
     * @Route("/", name="saison_hotel_index", methods={"GET"})
     */
    public function index(SaisonHotelRepository $saisonHotelRepository): Response
    {
        return $this->render('saison_hotel/index.html.twig', [
            'saison_hotels' => $saisonHotelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="saison_hotel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $saisonHotel = new SaisonHotel();
        $form = $this->createForm(SaisonHotelType::class, $saisonHotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($saisonHotel);
            $entityManager->flush();

            return $this->redirectToRoute('saison_hotel_index');
        }

        return $this->render('saison_hotel/new.html.twig', [
            'saison_hotel' => $saisonHotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="saison_hotel_show", methods={"GET"})
     */
    public function show(SaisonHotel $saisonHotel): Response
    {
        return $this->render('saison_hotel/show.html.twig', [
            'saison_hotel' => $saisonHotel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="saison_hotel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, SaisonHotel $saisonHotel): Response
    {
        $form = $this->createForm(SaisonHotelType::class, $saisonHotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('saison_hotel_index');
        }

        return $this->render('saison_hotel/edit.html.twig', [
            'saison_hotel' => $saisonHotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="saison_hotel_delete", methods={"DELETE"})
     */
    public function delete(Request $request, SaisonHotel $saisonHotel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$saisonHotel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($saisonHotel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('saison_hotel_index');
    }
}

templates/saison_hotel/_delete_form.html.twig
<form method="post" action="{{ path('saison_hotel_delete', {'id': saison_hotel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ saison_hotel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/saison_hotel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/saison_hotel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SaisonHotel{% endblock %}

{% block body %}
    <h1>Edit SaisonHotel</h1>

    {{ include('saison_hotel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('saison_hotel_index') }}">back to list</a>

    {{ include('saison_hotel/_delete_form.html.twig') }}
{% endblock %}

templates/saison_hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SaisonHotel index{% endblock %}

{% block body %}
    <h1>SaisonHotel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Hotel</th>
                <th>Prix</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for saison_hotel in saison_hotels %}
            <tr>
                <td>{{ saison_hotel.id }}</td>
                <td>{{ saison_hotel.id_hotel }}</td>
                <td>{{ saison_hotel.prix }}</td> 
                <td>{{ saison_hotel.dateDebut ? saison_hotel.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ saison_hotel.dateFin ? saison_hotel.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('saison_hotel_show', {'id': saison_hotel.id}) }}">show</a>
                    <a href="{{ path('saison_hotel_edit', {'id': saison_hotel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('saison_hotel_new') }}">Create new</a>
{% endblock %}

templates/saison_hotel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SaisonHotel{% endblock %}

{% block body %}
    <h1>Create new SaisonHotel</h1>

    {{ include('saison_hotel/_form.html.twig') }}

    <a href="{{ path('saison_hotel_index') }}">back to list</a>
{% endblock %}

templates/saison_hotel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SaisonHotel{% endblock %}

{% block body %}
    <h1>SaisonHotel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ saison_hotel.id }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ saison_hotel.prix }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ saison_hotel.dateDebut ? saison_hotel.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ saison_hotel.dateFin ? saison_hotel.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('saison_hotel_index') }}">back to list</a>

    <a href="{{ path('saison_hotel_edit', {'id': saison_hotel.id}) }}">edit</a>

    {{ include('saison_hotel/_delete_form.html.twig') }}
{% endblock %}